site_name: Kubernetes 进阶训练营
site_url: https://barry-boy.github.io/
repo_name: "GitHub"
repo_url: https://github.com/barry-boy/barry-boy.github.io
site_description: Project documentation with Markdown.
site_author: Li

theme:
  logo: material/logo.jpg

  name: "material"

  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"
  language: zh
  include_sidebar: true
  features:
    - header.autohide
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.top
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotate

  palette:
   # Light mode
   - media: "(prefers-color-scheme: light)"
     scheme: default
     primary: indigo
     accent: indigo
     toggle:
       icon: material/toggle-switch-off-outline
       name: 切换暗色主题

   # Dark mode
   - media: "(prefers-color-scheme: dark)"
     scheme: slate
     primary: blue
     accent: blue
     toggle:
       icon: material/toggle-switch
       name: 切换亮色主题

copyright: "Copyright &copy; 2022 lixie"



markdown_extensions:
  - admonition #MkDocs 警告框
  - footnotes #脚注
  - meta #自定义文章元数据
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线
  - def_list
  - tables
  - md_in_html
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true # hljs is used instead of pygment for TOML highlighting support
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  #  - markdown_include.include:
  #      base_path: content/includes/
  #      encoding: utf-8
  - toc: # 大纲
      permalink: true


nav:
    - 首页: index.md
    - 0、网络基础:
        - ZeroTier组网: network/ZeroTier.md
        - frp 内网穿透: network/frp.md
        - kubernetes 网络组件: network/3-network-docs.md
        - 科学上网: network/4-network-docs.md
    - 1、Linux: 
        - Linux 带外管理: ubuntu/ubuntu-bmc.md
        - Linux 系统安装: ubuntu/0-system-docs.md
        - Linux 系统管理-基础命令: ubuntu/linux01/Linux系统管理01——系统命令精讲.md
        - Linux 网络服务: ubuntu/network/1-network-docs.md

    - 2、容器运行时: 
        - Docker 基本管理: docker/docker-docs.md
        - lxcfs 介绍: docker/lxcfs.md
        - docker proxy代理: docker/docker-proxy-docs.md
        - docker 镜像构建: docker/docker-images-docs.md

    - 3、kubernetes:
        - 云原生简介及CNCF: basic/cncf-docs.md
        - K8S简介: k8s/base/k8s-overview.md
        - 集群部署: basic/3-k8s-systeminit-docs.md
        - K8S升级: basic/k8s-update.md
        - ETCD 简介与使用: basic/6-kubernetes-etcd-docs.md
        - COREDNS 简介与使用: basic/7-kubernetes-coredns-docs.md
       # - ETCD备份还原: basic/etcd.md
        - 资源清单: k8s/yaml/yaml.md
        - 资源限制: k8s/base/k8s-limit-docs.md
        - CKA考题: cks/cka.md
        - CKS考题: cks/cks.md
        - Kubernetes UI: basic/5-kubernetes-UI-docs.md
        - Rancher 升级: k8s/ui/rancher-update-docs.md
        - Kubernetes 节点维护: basic/7-kubernetes-update-docs.md
        - Helm 简介与安装: Helm/helm-install.md
        - Helm 配置grafana: Helm/helm.md
        - 处理k8s证书过期: k8s/other/k8s-ca-docs.md
        - 项目一: basic/4-ansible-install-k8s.md
        - 项目二: basic/9-install-keepalived-cluster.md

    - 4、运维开发:
         - Python 开发-基础语法: python/1-python-docs.md
         - GO开发-环境安装: go/go-base-docs.md
         - GO 开发-操作符和表达式: go/2-go-docs.md
         - 模块: python/module-docs.md
        
    - 5、数据库:
        - Mysql 数据库: k8s/mysql-operator/0-mysql-docs.md
        - Mysql-operator: k8s/mysql-operator/1-install-mysql-operator.md
        - Mysql 备份恢复: k8s/mysql-operator/2-mysql-backup-docs.md
        - 数据库问题处理: k8s/mysql-operator/3-mysql-backup-error-docs.md
        - 缓存加速: Storage/redis-docs.md
        - redis 集群篇: Storage/redis-cluster-docs.md
        - redis 持久化: redis/redis-save-docs.md
 
    - 6、存储服务: 
        - 固态 ssd : Storage/disk-ssd-docs.md
        - 分布式存储: Storage/rook-ceph.md
        - ceph 命令用法: Storage/ceph-cli-docs.md
        - Juicefs存储方案: Storage/Juicefs.md
        - Juicefs版本升级: Storage/juicefs-update.md
        - osd 性能测试: Storage/osd.md
        - pv/pvc简介: Storage/pv-rep.md
        - s3cmd 用法: Storage/s3-client-docs.md
        - ceph 存储修复: Storage/5-dev-docs.md

    - 7、虚拟化:
        - Proxmox虚拟化: vm/promox.md  

    - 8、Devops:
        - Github: Devops/github.md
        - Github仓库同步至Gitee: Devops/4-github-gitee-doc.md
        - Google 浏览器扩展: Devops/3-github-docs.md

    - 9、运维自动化:
        - Ansible 应用基础: ansible/ansible-case1.md
        - Ansible 高级用法: ansible/ansible-docs2.md
        - Ansible 安装: ansible/ansible-install-docs.md
        - Ansible playbook: ansible/ansible-playbook.md


    - 10、其他: 
        - kubeconfig 实践应用: Macuse/mac-kubeconfig.md
        - 边缘计算: k3s/k3s-install.md
        - k9s 实践应用: Macuse/mac-k9s-doc.md
        - Mac 制作ubuntu系统盘: Macuse/mac-usb-system.md
        - Mac vscode使用技巧: Macuse/mac-vscode.md
        - 天津集群: error/tjtu.md
        - Dev环境集群: error/dev.md
        - 误删除监控数据: error/delete-prometheus-db.md
        - Kubernetes pvc ubound: error/kubernetes-pvc-ubound-doc.md
        - dns 文件权限调整: error/centos-dns-error-docs.md

    - 关于我:
        - 我的2021: mylife/2021-life-docs.md
        - 我的2022: mylife/2022-life-docs.md
        - 我的2023: mylife/2023-life-docs.md


plugins:
  - search:
      prebuild_index: true
#  - minify:
#      minify_html: true

  # - pdf-export:
  #     verbose: true
  #     media_type: print
  #     enabled_if_env: ENABLE_PDF_EXPORT
  #     theme_handler_path: cinder.py

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cnych
    # - icon: fontawesome/brands/gitter
    #   link: https://gitter.im/squidfunk/mkdocs-material
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/cnych/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cnych
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/cnych


extra_css:
  - assets/stylesheets/extra.css # Our custom styles
  - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  - 'js/extra.js'
  - 'js/baidu-tongji.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  # - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  # - javascripts/tables.js
  # - assets/javascripts/hljs/highlight.pack.js # Download from https://highlightjs.org/download/ and enable YAML, TOML and Dockerfile
  # - assets/javascripts/extra.js

