site_name: Kubernetes 进阶训练营
repo_name: "GitHub"
repo_url: https://github.com/barry-boy/barry-boy.github.io
site_description: Project documentation with Markdown.
site_author: Li

theme:
  palette:
    scheme: default
  name: "material"
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"
  language: zh
  include_sidebar: true
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.top
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotate
  palette:
   # Light mode
   - media: "(prefers-color-scheme: light)"
     scheme: default
     primary: indigo
     accent: indigo
     toggle:
       icon: material/toggle-switch-off-outline
       name: 切换暗色主题

   # Dark mode
   - media: "(prefers-color-scheme: dark)"
     scheme: slate
     primary: blue
     accent: blue
     toggle:
       icon: material/toggle-switch
       name: 切换亮色主题

copyright: "Copyright &copy; 2022 lixie"


markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true # hljs is used instead of pygment for TOML highlighting support
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  #  - markdown_include.include:
  #      base_path: content/includes/
  #      encoding: utf-8
  - toc:
      permalink: true
      # slugify: !!python/name:pymdownx.slugs.uslugify_cased # Page tree

nav:
    - 首页: index.md
    - 操作系统: 
        - Linux 带外管理: ubuntu/ubuntu-bmc.md
        - Linux 系统安装: ubuntu/0-system-docs.md
        - Linux 系统管理-基础命令: ubuntu/linux01/Linux系统管理01——系统命令精讲.md
        - Linux 网络服务: ubuntu/network/1-network-docs.md

    - 容器运行时: 
        - Docker 基本管理: docker/docker-docs.md
        - lxcfs 介绍: docker/lxcfs.md
        - docker 实现翻墙 pull 镜像: docker/3-docker-docs.md
    - 基础:
        - 云原生简介: basic/cncf.md
        - K8S简介: k8s/base/k8s-overview.md
        - 集群部署: basic/3-k8s-systeminit-docs.md
        - K8S升级: basic/k8s-update.md
        - ETCD 简介与使用: basic/6-kubernetes-etcd-docs.md
        - COREDNS 简介与使用: basic/7-kubernetes-coredns-docs.md
       # - ETCD备份还原: basic/etcd.md
        - 资源清单: k8s/yaml/yaml.md
        - CKA考题: cks/cka.md
        - CKS考题: cks/cks.md
        - Kubernetes UI: basic/5-kubernetes-UI-docs.md
        - Kubernetes 节点维护: basic/7-kubernetes-update-docs.md
        - 项目一: basic/4-ansible-install-k8s.md
        - 项目二: basic/9-install-keepalived-cluster.md
     
    # - 控制器:
    #     - ReplicaSet: k8s/controller/rs.md
    #     - Deployment: k8s/controller/deployment.md
    #     - StatefulSet: k8s/controller/StatefulSet.md

    - K3S:
        - K3S安装: k3s/k3s-install.md
    # - 配置管理:
    #     - RBAC鉴权: config-admin/RBAC.md
    - 数据库:
        - Mysql-operator: k8s/mysql-operator/1-install-mysql-operator.md
    - 网络:
        - ZeroTier组网: network/ZeroTier.md
        - frp 内网穿透: network/frp.md
        - kubernetes 网络组件: network/3-network-docs.md
        - 科学上网: network/4-network-docs.md
        
    - 存储: 
        - 固态 ssd : Storage/disk-ssd-docs.md
        - rook-ceph简介: Storage/rook-ceph.md
        - Juicefs存储: Storage/Juicefs.md
        - 缓存加速: Storage/redis-docs.md
        - osd 性能测试: Storage/osd.md
        - pv/pvc简介: Storage/pv-rep.md
        - s3cmd 用法: Storage/s3-client-docs.md

        - ceph 存储修复: Storage/5-dev-docs.md
    - 虚拟化:
        - Proxmox虚拟化: vm/promox.md  
    - Devops:
        - Github: Devops/github.md
        - Github仓库同步至Gitee: Devops/4-github-gitee-doc.md
        - Google 浏览器扩展: Devops/3-github-docs.md
    # - 日志:
    #     - rsyslog日志服务管理: log/rsyslog.md

    - Ansible自动化:
        - Ansible 应用基础: ansible/ansible-case1.md
        - Ansible 高级用法: ansible/ansible-docs2.md
    - Helm:
        - Helm 简介与安装: Helm/helm-install.md
        - Helm 配置grafana: Helm/helm.md
    # - monitor:
    #     - prometheus 监控: monitor/prometheus.md
    - Python 自动化:
         - 模块：python/module-docs.md

    - 排错技巧: 
        - 天津集群: error/tjtu.md
        - Dev环境集群: error/dev.md
        - 误删除监控数据: error/delete-prometheus-db.md
        - Kubernetes pvc ubound: error/kubernetes-pvc-ubound-doc.md
 

    - 使用技巧: 
        - kubeconfig 实践应用: Macuse/mac-kubeconfig.md
        - k9s 实践应用: Macuse/mac-k9s-doc.md
        - Mac 制作ubuntu系统盘: Macuse/mac-usb-system.md
        - Mac vscode使用技巧: Macuse/mac-vscode.md


    - 工作生活:
        - 我的2021: mylife/life-docs1.md
        - 我的2022: mylife/2022-life-docs.md


plugins:
  - search:
      prebuild_index: true
#  - minify:
#      minify_html: true

  # - pdf-export:
  #     verbose: true
  #     media_type: print
  #     enabled_if_env: ENABLE_PDF_EXPORT
  #     theme_handler_path: cinder.py

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cnych
    # - icon: fontawesome/brands/gitter
    #   link: https://gitter.im/squidfunk/mkdocs-material
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/cnych/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cnych
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/cnych
extra_css:
  - assets/stylesheets/extra.css # Our custom styles
  - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  - 'js/extra.js'
  - 'js/baidu-tongji.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  # - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  # - javascripts/tables.js
  # - assets/javascripts/hljs/highlight.pack.js # Download from https://highlightjs.org/download/ and enable YAML, TOML and Dockerfile
  # - assets/javascripts/extra.js


