site_name: Kubernetes 进阶训练营
repo_name: "GitHub"
repo_url: https://github.com/lixie021/lixie021.github.io
site_description: Project documentation with Markdown.
site_author: Li

theme:
  palette:
    scheme: default
  name: "material"
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"
  language: zh
  include_sidebar: true
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.top
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotate
  palette:
   # Light mode
   - media: "(prefers-color-scheme: light)"
     scheme: default
     primary: indigo
     accent: indigo
     toggle:
       icon: material/toggle-switch-off-outline
       name: 切换暗色主题

   # Dark mode
   - media: "(prefers-color-scheme: dark)"
     scheme: slate
     primary: blue
     accent: blue
     toggle:
       icon: material/toggle-switch
       name: 切换亮色主题

copyright: "Copyright &copy; 2022 lixie"

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true # hljs is used instead of pygment for TOML highlighting support
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  #  - markdown_include.include:
  #      base_path: content/includes/
  #      encoding: utf-8
  - toc:
      permalink: true
      # slugify: !!python/name:pymdownx.slugs.uslugify_cased # Page tree



nav:
    - 首页: index.md
    - 操作系统: 
        - 服务器BMC带外管理: ubuntu/ubuntu-bmc.md
        - Ubuntu操作系统: ubuntu/ubuntu-system.md
        
        - Debian操作系统: Debian/Debian.md
    - 容器运行时: 
        - 容器基础: runtime/overview.md
        - lxcfs 介绍: docker/lxcfs.md
    - 基础:
        - 云原生简介: basic/cncf.md
        - K8S简介: k8s/base/k8s-overview.md
        - 集群部署: basic/k8s-systeminit.md
        - K8S升级: basic/k8s-update.md
        - ETCD备份还原: basic/etcd.md
        - 资源清单: k8s/yaml/yaml.md
    - 控制器:
        - ReplicaSet: k8s/controller/rs.md
        - Deployment: k8s/controller/deployment.md
        - StatefulSet: k8s/controller/StatefulSet.md

    - K3S:
        - K3S安装: k3s/k3s-install.md
    - 配置管理:
        - RBAC鉴权: config-admin/RBAC.md
    - 数据库:
        - Mysql-operator: k8s/mysql-operator/1-install-mysql-operator.md
    - 网络:
        - ZeroTier组网: network/ZeroTier.md

    - 存储: 
        - rook-ceph简介: Storage/rook-ceph.md
        - osd 性能测试: Storage/osd.md
        - pv/pvc简介: Storage/pv-rep.md
        - rook-ceph 版本升级: Storage/rook-ceph-update.md
        - Juicefs存储: Storage/Juicefs.md


    - 日志:
        - rsyslog日志服务管理: log/rsyslog.md

    - Ansible自动化:
        - 宁波港: ansible/ningbo-ansible.md
        - Ansible 案例: ansible/ansible-case1.md
    - Helm:
        - Helm 简介与安装: Helm/helm-install.md
        - Helm 配置grafana: Helm/helm.md
    - monitor:
        - prometheus 监控: monitor/prometheus.md

    - openbayes:
        - openbayes运维: openbayes/openbayes.md
        - openbayes produce 升级: openbayes/add-pc.md
    - 排错技巧: 
        - 天津集群: openbayes/tjtu.md
        - Dev环境集群: openbayes/dev.md
    
    - CKA/CKS考题: cks/cks.md

    - 使用技巧: 
        - Mac 小功能: easy/mac-easy.md
        - Mac 制作ubuntu系统盘: easy/mac-usb-system.md


# markdown_extensions:
  # - admonition
  # - codehilite:
  #     guess_lang: false
  #     linenums: false
  # - toc:
  #     permalink: true
  # - footnotes
  # - meta
  # - def_list
  # - pymdownx.arithmatex
  # - pymdownx.betterem:
  #     smart_enable: all
  # - pymdownx.caret
  # - pymdownx.critic
  # - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:pymdownx.emoji.to_png
  #     #emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #     #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
  #     #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
  #     #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
  #     #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  # - pymdownx.inlinehilite
  # - pymdownx.magiclink
  # - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.superfences
  # - pymdownx.tasklist
  # - pymdownx.tilde
  #   # - User Guide:

plugins:
  - search:
      prebuild_index: true
  - minify:
      minify_html: true

  # - pdf-export:
  #     verbose: true
  #     media_type: print
  #     enabled_if_env: ENABLE_PDF_EXPORT
  #     theme_handler_path: cinder.py

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cnych
    # - icon: fontawesome/brands/gitter
    #   link: https://gitter.im/squidfunk/mkdocs-material
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/cnych/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cnych
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/cnych
extra_css:
  - assets/stylesheets/extra.css # Our custom styles
  - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  - 'js/extra.js'
  - 'js/baidu-tongji.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  # - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  # - javascripts/tables.js
  # - assets/javascripts/hljs/highlight.pack.js # Download from https://highlightjs.org/download/ and enable YAML, TOML and Dockerfile
  # - assets/javascripts/extra.js

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# https://facelessuser.github.io/pymdown-extensions/




#
#plugins:
#  - search:
#      prebuild_index: true
#  - minify:
#      minify_html: true
#
#  # - pdf-export:
#  #     verbose: true
#  #     media_type: print
#  #     enabled_if_env: ENABLE_PDF_EXPORT
#  #     theme_handler_path: cinder.py
#
## Customization
#extra:
#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/cnych
#    # - icon: fontawesome/brands/gitter
#    #   link: https://gitter.im/squidfunk/mkdocs-material
#    - icon: fontawesome/brands/docker
#      link: https://hub.docker.com/r/cnych/
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/cnych
#    - icon: fontawesome/brands/instagram
#      link: https://instagram.com/cnych
#

#
## https://squidfunk.github.io/mkdocs-material/extensions/admonition/
## https://facelessuser.github.io/pymdown-extensions/
#markdown_extensions:
#  - attr_list
#  - admonition
#  - footnotes
#  - pymdownx.details
#  - pymdownx.inlinehilite
#  - pymdownx.highlight:
#      use_pygments: true # hljs is used instead of pygment for TOML highlighting support
#  - pymdownx.smartsymbols
#  - pymdownx.superfences
#  - pymdownx.tasklist
#  - pymdownx.snippets:
#      check_paths: true
#  #  - markdown_include.include:
#  #      base_path: content/includes/
#  #      encoding: utf-8


#nav:
#  - "首页": "index.md"
#  - "容器运行时":
#      - "容器运行时介绍": "runtime/overview.md"
#      - "Containerd的使用": "runtime/usage.md"
#      - "命令行工具Nerdctl": "runtime/nerdctl.md"
#      - "CGroups与Namespaces": "runtime/cgroups-namespaces.md"
#      # - 'Dockerfile': 'runtime/dockerfile-usage.md'
#      # - 'Dockerfile最佳实践': 'runtime/dockerfile-practice.md'
#      # - '镜像构建': 'runtime/build.md'
#  - "基础": 
#      - "K8S简介": "basic/overview.md"
#      - "集群部署": "k3s/basic/k8s-update.md"
#      - "资源清单": "basic/yaml.md"
#      - "Pod原理": "basic/pod.md"
#      - "Pod生命周期": "basic/pod-life.md"
#      - "Pod使用进阶": "basic/pod-deep.md"
#      - "Etcd备份还原": "docs/k8s.md"
