site_name: Kubernetes 进阶训练营(第3期)
#site_url: https://www.qikqiak.com/k3s
repo_name: "GitHub"
repo_url: "https://github.com/cnych/qikqiak.com"

#docs_dir: "content"

theme:
  name: "material"
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"
#  custom_dir: "theme"
  language: zh
  include_sidebar: true
#  favicon: assets/img/train.logo.png
#  logo: assets/img/train.logo.png
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.top
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotate
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换暗色主题

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: 切换亮色主题

copyright: "Copyright &copy; 2021 优点知识"

plugins:
  - search:
      prebuild_index: true
  - minify:
      minify_html: true

  # - pdf-export:
  #     verbose: true
  #     media_type: print
  #     enabled_if_env: ENABLE_PDF_EXPORT
  #     theme_handler_path: cinder.py

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cnych
    # - icon: fontawesome/brands/gitter
    #   link: https://gitter.im/squidfunk/mkdocs-material
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/cnych/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cnych
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/cnych

extra_css:
  - assets/stylesheets/extra.css # Our custom styles
  - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  - assets/javascripts/hljs/highlight.pack.js # Download from https://highlightjs.org/download/ and enable YAML, TOML and Dockerfile
  - assets/javascripts/extra.js

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true # hljs is used instead of pygment for TOML highlighting support
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  #  - markdown_include.include:
  #      base_path: content/includes/
  #      encoding: utf-8
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify_cased # Page tree

nav:
  - '首页': "index.md"
  - '容器运行时':
      - '容器运行时介绍': "runtime/overview.md"
#      - "Containerd的使用": "runtime/usage.md"
#      - "命令行工具Nerdctl": "runtime/nerdctl.md"
#      - "CGroups与Namespaces": "runtime/cgroups-namespaces.md"
#      # - 'Dockerfile': 'runtime/dockerfile-usage.md'
#      # - 'Dockerfile最佳实践': 'runtime/dockerfile-practice.md'
#      # - '镜像构建': 'runtime/build.md'
#  - "基础":
#      - "K8S简介": "basic/overview.md"
#      - "集群部署": "basic/install.md"
#      - "资源清单": "basic/yaml.md"
#      - "Pod原理": "basic/pod.md"
#      - "Pod生命周期": "basic/pod-life.md"
#      - "Pod使用进阶": "basic/pod-deep.md"
#      - "Etcd备份还原": "basic/etcd.md"
#  - "控制器":
#      - "ReplicaSet": "controller/replicaset.md"
#      - "Deployment": "controller/deployment.md"
#      - "StatefulSet": "controller/statefulset.md"
#      - "DaemonSet": "controller/daemonset.md"
#      - "Job": "controller/job.md"
#      - "HPA": "controller/hpa.md"
#      - "Admission": "controller/admission.md"
#      - "Crd": "controller/crd.md"
#      - "OpenKruise": "controller/openkruise.md"
#  - "配置管理":
#      - "ConfigMap": "config/configmap.md"
#      - "Secret": "config/secret.md"
#      # - 'ServiceAccount': 'config/serviceaccount.md'
#      - "RBAC": "security/rbac.md"
#      - "Security Context": "security/security-context.md"
#      - "OPA": "security/opa.md"
#      - "Kyverno": "security/kyverno.md"
#  - "网络":
#      #     - '网络插件': 'network/flannel.md'
#      #     - '网络策略': 'network/networkpolicy.md'
#      - "Service": "network/service.md"
#      - "DNS": "network/dns.md"
#      - "LocalDNS": "network/localdns.md"
#      - "Ingress": "network/ingress.md"
#      - "Ingress-nginx": "network/ingress-nginx.md"
#      - "Traefik": "network/traefik.md"
#      - "Gateway API": "network/gateway-api.md"
#      - "APISIX": "network/apisix.md"
#  - "调度器":
#      - "调度器介绍": "scheduler/overview.md"
#      - "亲合性调度": "scheduler/usage.md"
#      - "拓扑分布约束": "scheduler/topology.md"
#      - "Descheduler": "scheduler/descheduler.md"
#      - "服务质量": "scheduler/qos.md"
#  - "存储":
#      - "本地存储": "storage/local.md"
#      - "NFS存储": "storage/nfs.md"
#      - "存储插件": "storage/plugin.md"
#      - "Longhorn": "storage/longhorn.md"
#  - "Helm":
#      - "Helm": "helm/index.md"
#      - "Charts": "helm/charts.md"
#      - "模板开发":
#          - "内置对象": "helm/templates/objects.md"
#          - "Values": "helm/templates/values.md"
#          - "函数与管道": "helm/templates/function.md"
#          - "流程控制": "helm/templates/flow.md"
#          - "变量": "helm/templates/variables.md"
#          - "命名模板": "helm/templates/named_templates.md"
#          - "访问文件": "helm/templates/access_files.md"
#          - "NOTES.txt": "helm/templates/notes_files.md"
#          - "子chart与全局值": "helm/templates/subcharts_and_globals.md"
#          - "模板调试": "helm/templates/debug.md"
#          - "Chart Hooks": "helm/templates/hooks.md"
#      - "示例": "helm/demo.md"
#  - "监控":
#      - "Prometheus": "monitor/prometheus.md"
#      - "PromQL": "monitor/promql.md"
#      - "Grafana": "monitor/grafana.md"
#      - "AlertManager": "monitor/alertmanager.md"
#      - "VictoriaMetrics": "monitor/victorialmetrics.md"
#      - "Prometheus Operator":
#          - "安装": "monitor/operator/install.md"
#          - "自定义监控报警": "monitor/operator/custom.md"
#          - '高级配置': 'monitor/operator/advance.md'
#      - "Probe": "monitor/operator/probe.md"
#  #     - 'Prometheus Adpater': 'monitor/adapter.md'
#
#  - '日志':
#      - '日志收集架构': 'logging/arch.md'
#      - 'EFK': 'logging/efk.md'
#      - 'Fluentd': 'logging/fluentd.md'
#      - 'Loki':
#        - 'Loki': 'logging/loki/overview.md'
#        - 'Promtail': 'logging/loki/promtail.md'
#        - '读写分离模式': 'logging/loki/simple-scalable.md'
#        - '微服务模式': 'logging/loki/distributed.md'
#        - '配置文件': 'logging/loki/config.md'
#        - '日志报警': 'logging/loki/alert.md'
#        - 'LogQL': 'logging/loki/logql.md'
#  - 'DevOps':
#      - 'Jenkins': 'devops/jenkins.md'
#      - 'GitLab': 'devops/gitlab.md'
#  #     - 'Harbor': 'devops/harbor.md'
#  #     - 'Jenkins 流水线': 'devops/pipeline.md'
#  #     - 'Tekton':
#  #       - '安装': 'devops/tekton/overview.md'
#  #       - 'Task任务': 'devops/tekton/task.md'
#  #       - 'Pipeline流水线': 'devops/tekton/pipeline.md'
#  #       - '触发器与事件监听器': 'devops/tekton/trigger.md'
#  #       - '项目实战': 'devops/tekton/action.md'
#  #     - 'GitOps':
#  #       - 'GitOps 是什么？': 'devops/gitops/overview.md'
#  #       - 'Argo CD': 'devops/gitops/argocd.md'
#  #       - 'Argo Rollouts': 'devops/gitops/argorollouts.md'
#  # - 'Istio':
#  #     - 'Istio 简介': 'istio/install.md'
#  #     - '流量管理': 'istio/traffic.md'
#  #     - '可观测性': 'istio/observability.md'
#  #     - '安全管控': 'istio/security.md'
#  #     - 'Certmanager': 'istio/cert-manager.md'
#  # - '技巧':
#  #     - '技巧': 'skill/index.md'
#  #     # - '集群升级': 'maintain/update.md'
#  #     # - '升级为集群': 'maintain/cluster.md'
#  #     - '资源预留': 'maintain/reserved.md'
#  #     - '部署高可用集群': 'maintain/ha.md'
#  #     - 'kubectl 技巧': 'maintain/kubectl.md'
#  #     - '集群备份还原': 'maintain/velero.md'
#  # - '多租户':
#  #     - '多租户介绍': 'tenant/index.md'
#  #     - '资源配额': 'tenant/quota.md'
#  #     - 'Pod 安全策略': 'tenant/psp.md'
#  # - 'Operator':
#  #     - 'CRD': 'operator/crd.md'
#  #     - 'Operator': 'operator/operator.md'
#  # - '源码':
#  #     - 'kubelet 源码': 'code/kubelet.md'
#  #     - 'client-go':
#  #         - 'workqueue': 'code/client-go/workqueue.md'
#  #         - 'Indexer': 'code/client-go/indexer.md'
#  #         - 'DeltaFIFO': 'code/client-go/deltafifo.md'

