name: Sync to Gitee

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2

      - name: Sync to Gitee
        run: |
          git remote add gitee https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/awxie/lvycoder.github.io.git
          git push gitee master --force
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}