name: Update Notion

on:
  push:
    branches:
      - master  # 监视 main 分支的变化

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Notion page
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_PAGE_ID: ab213ac987f94e5586222df9fe8db4ad  # 用实际的 Notion 页面 ID 替换
      run: |
        echo "Updating Notion page..."
        content=$(<README.md)  # 假设你要同步 README.md 文件的内容
        curl -X PATCH "https://api.notion.com/v1/pages/$NOTION_PAGE_ID" \
          -H "Authorization: Bearer $NOTION_API_KEY" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{"properties": {"title": {"title": [{"text": {"content": "New Content"}}]}}, "children": [{"object": "block", "type": "paragraph", "paragraph": {"text": [{"type": "text", "text": {"content": "'"$content"'"}}]}}]}'
